name: archlinux arm build nightly

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      wifi_ssid:
        description: 'WiFi SSID (留空默认为ffashion)'
        required: false
        default: 'ffashion'
      wifi_password:
        description: 'WiFi Password (留空默认为)'
        required: false
        default: 'ffashionffashion'
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

env:
    DEFAULT_WIFI_SSID: 'ffashion'
    DEFAULT_WIFI_PASSWORD: 'ffashionffashion'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup variables
        run: |
          echo RELEASE=$(date +%Y\/%m\/%d) >> $GITHUB_ENV

      - name: Set WiFi environment variables
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            SSID="${{ github.event.inputs.wifi_ssid }}"
            PASS="${{ github.event.inputs.wifi_password }}"
          else
            SSID="${{ env.DEFAULT_WIFI_SSID }}"
            PASS="${{ env.DEFAULT_WIFI_PASSWORD }}"
          fi
          echo "WIFI_SSID=$SSID" >> $GITHUB_ENV
          echo "WIFI_PASSWORD=$PASS" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install make mkbootimg build-essential \
            libncurses5-dev bison flex libssl-dev device-tree-compiler \
            gcc-arm-none-eabi gcc-aarch64-linux-gnu bc libfdt-dev \
            libarchive-tools arch-install-scripts qemu-user-static

      - name: Initialization submodule
        run: git submodule update --init --depth=1

      - name: Build packets
        run: |
              sudo WIFI_SSID="$WIFI_SSID" WIFI_PASSWORD="$WIFI_PASSWORD" bash -x ${{github.workspace}}/build.sh


      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 3dprinter-archlinux-wifistick-${{github.run_id}}-${{github.sha}}
          path: |
            ${{github.workspace}}/build/aboot.img
            ${{github.workspace}}/build/boot.img
            ${{github.workspace}}/build/rootfs.img.zst
            ${{github.workspace}}/build/aboot.img.sha256sum
            ${{github.workspace}}/build/boot.img.sha256sum
            ${{github.workspace}}/build/rootfs.img.zst.sha256sum
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          body: ${{env.RELEASE}}
          tag_name: ${{env.RELEASE}}
          draft: false
          prerelease: false
          files: |
            ${{github.workspace}}/build/aboot.img
            ${{github.workspace}}/build/boot.img
            ${{github.workspace}}/build/rootfs.img.zst
            ${{github.workspace}}/build/aboot.img.sha256sum
            ${{github.workspace}}/build/boot.img.sha256sum
            ${{github.workspace}}/build/rootfs.img.zst.sha256sum

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          keep_latest: 1
          delete_tags: true
      - name: debug
        if: ${{ failure() }}
        uses: csexton/debugger-action@master
